/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as TracksNewRouteImport } from './routes/tracks.new'
import { Route as TracksSlugRouteImport } from './routes/tracks.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated.host'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedHostEventsNewRouteImport } from './routes/_authenticated.host.events.new'
import { Route as AuthenticatedHostCompetitionsNewRouteImport } from './routes/_authenticated.host.competitions.new'
import { Route as AuthenticatedHostEventsSlugSubmissionsRouteImport } from './routes/_authenticated.host.events.$slug.submissions'
import { Route as AuthenticatedHostCompetitionsSlugRoundsRouteImport } from './routes/_authenticated.host.competitions.$slug.rounds'
import { Route as AuthenticatedHostCompetitionsSlugEntriesRouteImport } from './routes/_authenticated.host.competitions.$slug.entries'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksNewRoute = TracksNewRouteImport.update({
  id: '/tracks/new',
  path: '/tracks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksSlugRoute = TracksSlugRouteImport.update({
  id: '/tracks/$slug',
  path: '/tracks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompetitionsRoute,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostEventsNewRoute =
  AuthenticatedHostEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostCompetitionsNewRoute =
  AuthenticatedHostCompetitionsNewRouteImport.update({
    id: '/competitions/new',
    path: '/competitions/new',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostEventsSlugSubmissionsRoute =
  AuthenticatedHostEventsSlugSubmissionsRouteImport.update({
    id: '/events/$slug/submissions',
    path: '/events/$slug/submissions',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostCompetitionsSlugRoundsRoute =
  AuthenticatedHostCompetitionsSlugRoundsRouteImport.update({
    id: '/competitions/$slug/rounds',
    path: '/competitions/$slug/rounds',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostCompetitionsSlugEntriesRoute =
  AuthenticatedHostCompetitionsSlugEntriesRouteImport.update({
    id: '/competitions/$slug/entries',
    path: '/competitions/$slug/entries',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/host': typeof AuthenticatedHostRouteWithChildren
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks/new': typeof TracksNewRoute
  '/u/$username': typeof UUsernameRoute
  '/host/competitions/new': typeof AuthenticatedHostCompetitionsNewRoute
  '/host/events/new': typeof AuthenticatedHostEventsNewRoute
  '/host/competitions/$slug/entries': typeof AuthenticatedHostCompetitionsSlugEntriesRoute
  '/host/competitions/$slug/rounds': typeof AuthenticatedHostCompetitionsSlugRoundsRoute
  '/host/events/$slug/submissions': typeof AuthenticatedHostEventsSlugSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/host': typeof AuthenticatedHostRouteWithChildren
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks/new': typeof TracksNewRoute
  '/u/$username': typeof UUsernameRoute
  '/host/competitions/new': typeof AuthenticatedHostCompetitionsNewRoute
  '/host/events/new': typeof AuthenticatedHostEventsNewRoute
  '/host/competitions/$slug/entries': typeof AuthenticatedHostCompetitionsSlugEntriesRoute
  '/host/competitions/$slug/rounds': typeof AuthenticatedHostCompetitionsSlugRoundsRoute
  '/host/events/$slug/submissions': typeof AuthenticatedHostEventsSlugSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/host': typeof AuthenticatedHostRouteWithChildren
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks/new': typeof TracksNewRoute
  '/u/$username': typeof UUsernameRoute
  '/_authenticated/host/competitions/new': typeof AuthenticatedHostCompetitionsNewRoute
  '/_authenticated/host/events/new': typeof AuthenticatedHostEventsNewRoute
  '/_authenticated/host/competitions/$slug/entries': typeof AuthenticatedHostCompetitionsSlugEntriesRoute
  '/_authenticated/host/competitions/$slug/rounds': typeof AuthenticatedHostCompetitionsSlugRoundsRoute
  '/_authenticated/host/events/$slug/submissions': typeof AuthenticatedHostEventsSlugSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/competitions'
    | '/events'
    | '/explore'
    | '/sitemap.xml'
    | '/dashboard'
    | '/host'
    | '/competitions/$slug'
    | '/events/$slug'
    | '/tracks/$slug'
    | '/tracks/new'
    | '/u/$username'
    | '/host/competitions/new'
    | '/host/events/new'
    | '/host/competitions/$slug/entries'
    | '/host/competitions/$slug/rounds'
    | '/host/events/$slug/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/competitions'
    | '/events'
    | '/explore'
    | '/sitemap.xml'
    | '/dashboard'
    | '/host'
    | '/competitions/$slug'
    | '/events/$slug'
    | '/tracks/$slug'
    | '/tracks/new'
    | '/u/$username'
    | '/host/competitions/new'
    | '/host/events/new'
    | '/host/competitions/$slug/entries'
    | '/host/competitions/$slug/rounds'
    | '/host/events/$slug/submissions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/competitions'
    | '/events'
    | '/explore'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/host'
    | '/competitions/$slug'
    | '/events/$slug'
    | '/tracks/$slug'
    | '/tracks/new'
    | '/u/$username'
    | '/_authenticated/host/competitions/new'
    | '/_authenticated/host/events/new'
    | '/_authenticated/host/competitions/$slug/entries'
    | '/_authenticated/host/competitions/$slug/rounds'
    | '/_authenticated/host/events/$slug/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompetitionsRoute: typeof CompetitionsRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TracksSlugRoute: typeof TracksSlugRoute
  TracksNewRoute: typeof TracksNewRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/new': {
      id: '/tracks/new'
      path: '/tracks/new'
      fullPath: '/tracks/new'
      preLoaderRoute: typeof TracksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$slug': {
      id: '/tracks/$slug'
      path: '/tracks/$slug'
      fullPath: '/tracks/$slug'
      preLoaderRoute: typeof TracksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof CompetitionsRoute
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/host/events/new': {
      id: '/_authenticated/host/events/new'
      path: '/events/new'
      fullPath: '/host/events/new'
      preLoaderRoute: typeof AuthenticatedHostEventsNewRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/competitions/new': {
      id: '/_authenticated/host/competitions/new'
      path: '/competitions/new'
      fullPath: '/host/competitions/new'
      preLoaderRoute: typeof AuthenticatedHostCompetitionsNewRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/events/$slug/submissions': {
      id: '/_authenticated/host/events/$slug/submissions'
      path: '/events/$slug/submissions'
      fullPath: '/host/events/$slug/submissions'
      preLoaderRoute: typeof AuthenticatedHostEventsSlugSubmissionsRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/competitions/$slug/rounds': {
      id: '/_authenticated/host/competitions/$slug/rounds'
      path: '/competitions/$slug/rounds'
      fullPath: '/host/competitions/$slug/rounds'
      preLoaderRoute: typeof AuthenticatedHostCompetitionsSlugRoundsRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/competitions/$slug/entries': {
      id: '/_authenticated/host/competitions/$slug/entries'
      path: '/competitions/$slug/entries'
      fullPath: '/host/competitions/$slug/entries'
      preLoaderRoute: typeof AuthenticatedHostCompetitionsSlugEntriesRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
  }
}

interface AuthenticatedHostRouteChildren {
  AuthenticatedHostCompetitionsNewRoute: typeof AuthenticatedHostCompetitionsNewRoute
  AuthenticatedHostEventsNewRoute: typeof AuthenticatedHostEventsNewRoute
  AuthenticatedHostCompetitionsSlugEntriesRoute: typeof AuthenticatedHostCompetitionsSlugEntriesRoute
  AuthenticatedHostCompetitionsSlugRoundsRoute: typeof AuthenticatedHostCompetitionsSlugRoundsRoute
  AuthenticatedHostEventsSlugSubmissionsRoute: typeof AuthenticatedHostEventsSlugSubmissionsRoute
}

const AuthenticatedHostRouteChildren: AuthenticatedHostRouteChildren = {
  AuthenticatedHostCompetitionsNewRoute: AuthenticatedHostCompetitionsNewRoute,
  AuthenticatedHostEventsNewRoute: AuthenticatedHostEventsNewRoute,
  AuthenticatedHostCompetitionsSlugEntriesRoute:
    AuthenticatedHostCompetitionsSlugEntriesRoute,
  AuthenticatedHostCompetitionsSlugRoundsRoute:
    AuthenticatedHostCompetitionsSlugRoundsRoute,
  AuthenticatedHostEventsSlugSubmissionsRoute:
    AuthenticatedHostEventsSlugSubmissionsRoute,
}

const AuthenticatedHostRouteWithChildren =
  AuthenticatedHostRoute._addFileChildren(AuthenticatedHostRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHostRoute: typeof AuthenticatedHostRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHostRoute: AuthenticatedHostRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CompetitionsRouteChildren {
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
}

const CompetitionsRouteChildren: CompetitionsRouteChildren = {
  CompetitionsSlugRoute: CompetitionsSlugRoute,
}

const CompetitionsRouteWithChildren = CompetitionsRoute._addFileChildren(
  CompetitionsRouteChildren,
)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CompetitionsRoute: CompetitionsRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  ExploreRoute: ExploreRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TracksSlugRoute: TracksSlugRoute,
  TracksNewRoute: TracksNewRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
